services:
  postgres:
    image: postgres:18
    container_name: aluguei-postgres
    environment:
      POSTGRES_DB: aluguei_db
      POSTGRES_USER: aluguei_user
      POSTGRES_PASSWORD: aluguei_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aluguei_user -d aluguei_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: aluguei-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: